name: Build Apps

on:
push:
branches: [ main ]

jobs:

build-windows:
runs-on: windows-latest
steps:
- uses: actions/checkout@v3

```
  - uses: actions/setup-node@v3
    with:
      node-version: 16

  - run: npm install

  - run: npx electron-builder --win --x64 --ia32 --publish never

  - uses: actions/upload-artifact@v4
    with:
      name: Jonah-Windows
      path: dist/*.exe
```

build-mac:
runs-on: macos-latest
steps:
- uses: actions/checkout@v3

```
  - uses: actions/setup-node@v3
    with:
      node-version: 16

  - run: npm install

  - run: npx electron-builder --mac --publish never

  - uses: actions/upload-artifact@v4
    with:
      name: Jonah-Mac
      path: dist/*.dmg
```

build-linux:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3

```
  - uses: actions/setup-node@v3
    with:
      node-version: 16

  - run: npm install

  - run: npx electron-builder --linux --publish never

  - uses: actions/upload-artifact@v4
    with:
      name: Jonah-Linux
      path: dist/*.AppImage
```
