name: Build Windows App

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Windows installer
        run: npx electron-builder --win --x64 --ia32 --publish never

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Jonah-Windows
          path: dist/*.exe
